# Generated by Django 2.2.7 on 2019-12-05 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20191205_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserJobPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_preference', models.CharField(choices=[('none', ''), ('software-developer', 'Software Developer'), ('banker', 'Banker'), ('business-development', 'Business Development'), ('android', 'Android'), ('web', 'Web Design'), ('ui-ux', 'UI/UX'), ('teaching', 'Teaching'), ('training', 'Training'), ('garments', 'Garments')], default='none', max_length=255)),
                ('status', models.BooleanField(blank=True, default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
